on: [push]

jobs:
   analyze_repo_meta:
      runs-on: windows-latest
      env:
         GITHUB_secrets: ${{ toJSON(secrets) }}
      name: Analyze repository
      steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Run nodejs
           run: node .\dist\index.js
